app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('submit/', views.submit, name='submit'),
    path('master/', views.master, name='master'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
]

storychain/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.
class Story(models.Model):
    title = models.CharField(max_length=20)
    text = models.TextField(max_length=100)
    created_at = models.DateTimeField(auto_now=True)
    param = (
        ('false', u'物語は続く'),
        ('true', u'物語の終了')
    )
    is_finish = models.CharField(max_length=5, choices=param)
    def __str__(self):
        return self.title

class Storybone(models.Model):
    starttext = models.TextField(max_length=100)
    lasttext = models.TextField(max_length=100)

    def __str__(self):
        return self.starttext

app/forms.py
from django.forms import ModelForm
from .models import Story, Storybone

class StoryForm(ModelForm):
    class Meta:
        model = Story
        fields = ['title', 'text', 'is_finish']

class StoryboneForm(ModelForm):
    class Meta:
        model = Storybone
        fields = ['starttext', 'lasttext']

app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Story, Storybone
from .forms import StoryForm, StoryboneForm

def index(request):
    storybone = Storybone.objects.get()
    storys = Story.objects.all().order_by('created_at').order_by('id')[0:20]
    return render(request, 'app/index.html', {'storys': storys, 'storybone': storybone})

def aboutus(request):
    return render(request, 'app/aboutus.html')

def submit(request):
    if request.method == 'POST':
        form = StoryForm(request.POST, request.FILES)
        if form.is_valid() and Story.objects.all().count() < 50:
            story = form.save()
            messages.success(request, "投稿が完了しました")
        else:
            messages.error(request, "保存されるメッセージ数の上限に達しています。")
        return redirect('app:index')
    else:
        form = StoryForm()
    return render(request, 'app/submit.html', {'form':form})

@login_required
def master(request):
    if request.method == 'POST':
        form = StoryboneForm(request.POST, request.FILES)
        if form.is_valid():
            storys = Story.objects.all()
            storys.delete()
            prev_storybone = Storybone.objects.all()
            prev_storybone.delete()
            storybone = form.save()
            messages.success(request, "物語の骨子が作成されました。")
        return redirect('app:index')
    else:
        form = StoryboneForm()
    return render(request, 'app/master.html', {'form':form})

app/templates/app/aboutus.html
{% extends 'app/base.html' %}
{% block content %}
<h2>StoryChainとは</h2>

<p>Djangoの勉強用？として制作した、チュートリアルを少しいじっただけのwebサービスです。</p>
<p>せっかくなので、「スタートの文」と「ゴールの文」をみなさまの100文字の力で「風が吹けば桶屋が儲かる」風につなげよう！みたいなサービスにしてみました。</p>
<p>今後DjangoやCSSの勉強が進むにつれ、機能が追加されたり、見栄えが良くなっていくかもしれません。</p>

<h3>注意事項など</h3>
<ul>
    <li>書き込み内容は自己責任です。気をつけてください。</li>
    <li>このサイトへの書き込みによって発生した、いかなる損害に対してもサイト制作者は責任をとりません。</li>
</ul>
{% endblock %}

app/templates/app/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>StoryChain</title>
</head>
<body>
    <h1><a href="{% url 'app:index' %}"">StoryChain</a></h1>
    <a href="{% url 'app:aboutus' %}">StoryChainとは</a>
    <a href="{% url 'app:submit' %}">投稿する</a>

    {% if request.user.is_authenticated %}
    <a href="{% url 'app:logout' %}">ログアウト</a>
    {% endif %}

    <div>
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>

    {% block content %}
    {% endblock %}
</body>
<footer>
    <a href="{% url 'app:master' %}">管理者用ページ</a>
</footer>
</html>

app/templates/app/index.html
{% extends 'app/base.html' %}
{% block content %}

<p>物語の開始の文は：<br>
    {{ storybone.starttext }}</p>
{% for story in storys %}
<div>
    {{ story.text }}
    {% if story.is_finish == 'true' %}
        <p>ここで物語は終了するようです・・・</p>
    {% endif %}
</div>
{% endfor %}
<p>物語の終了の文は：<br>
    {{ storybone.lasttext }}</p>
{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% block content %}

<form class="form-signin" method="post">
    {% csrf_token %}
    {% if form.errors %}
        <p>ユーザー名もしくはパスワードが違っています。もう一度入力してください。</p>
    {% endif %}
    <h2>ログイン</h2>
    <label>ユーザー名</label>
    <input name="username">
    <br>
    <label>パスワード</label>
    <input type="password" name="password">
    <br>
    <input type="submit" value="ログイン">
</form>

{% endblock %}

app/templates/app/master.html
{% extends 'app/base.html' %}
{% block content %}

<p>マスター用ページです</p>
<form action="{% url 'app:master' %}" method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <th>はじめの文</th>
                <td>{{ form.starttext }}</td>
            </tr>
            <tr>
                <th>最後の文</th>
                <td>{{ form.lasttext }}</td>
            </tr>
        </table>
        <button type="submit" class="btn">作成</button>
</form>
{% endblock %}

app/templates/app/submit.html
{% extends 'app/base.html' %}
{% block content %}


<form action="{% url 'app:submit' %}" method="POST">
    {% csrf_token %}
    <table>
        <tr>
            <th>タイトル</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ form.text }}</td>
        </tr>
        <tr>
            <th>物語の終了を宣言しますか？</th>
            <td>{{ form.is_finish }}</td>
        </tr>
    </table>
    <button type="submit" class="btn">投稿</button>
</form>
{% endblock %}